name: LIT MLIR Tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test-mlir:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/robertkq/picceler-ci:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure project
        run: cmake -S . -B build

      - name: Build project
        run: cmake --build build --parallel

      - name: Run mlir
        run: |
          cd build
          lit -v ./mlir